name: Pytest CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: urbs-env  # Name of the environment
          environment-file: urbs-env.yml
          python-version: 3.12.2  # Match Python version in urbs-env.yml
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda info --envs  # Check installed environments
          conda list  # Verify installed packages

