name: Ruff
on: [ push, pull_request ]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python (at least 3.12)
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'
